// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {time} from '../models';
import {model} from '../models';

export function CleanupOldMetrics(arg1:time.Duration):Promise<void>;

export function Create(arg1:model.Configuration):Promise<void>;

export function CreateConnection(arg1:string,arg2:string):Promise<model.Connection>;

export function CreateDevice(arg1:Record<string, string>):Promise<model.NetworkDevice>;

export function CreateReport(arg1:model.Reports):Promise<void>;

export function CreateTopologyElement(arg1:number):Promise<model.TopologyElement>;

export function DeleteConnection(arg1:number):Promise<void>;

export function DeleteReport(arg1:number):Promise<void>;

export function GetActive(arg1:number):Promise<model.Configuration>;

export function GetAllConnections():Promise<Array<model.Connection>>;

export function GetAllDevices():Promise<Array<model.NetworkDevice>>;

export function GetAllLogs():Promise<Array<model.NetworkLog>>;

export function GetAllMetrics():Promise<Array<model.Metric>>;

export function GetAllReports():Promise<Array<model.Reports>>;

export function GetAllTopology():Promise<Array<model.TopologyElement>>;

export function GetByDeviceID(arg1:number):Promise<Array<model.Configuration>>;

export function GetByName(arg1:string):Promise<model.User>;

export function GetConnectionById(arg1:number):Promise<void>;

export function GetConnectionsByDeviceId(arg1:number,arg2:number):Promise<model.Connection>;

export function GetDeviceById(arg1:number):Promise<model.NetworkDevice>;

export function GetLatestMetricsByDeviceId(arg1:number,arg2:number):Promise<Array<model.Metric>>;

export function GetLogsByDeviceId(arg1:number):Promise<Array<model.NetworkLog>>;

export function GetMetricsByDeviceId(arg1:number):Promise<Array<model.Metric>>;

export function GetMetricsByDeviceIdAndInterval(arg1:number,arg2:string,arg3:time.Time,arg4:time.Time):Promise<Array<model.Metric>>;

export function GetRecentLogs(arg1:number):Promise<Array<model.NetworkLog>>;

export function GetReport(arg1:number):Promise<model.Reports>;

export function Login(arg1:Record<string, string>):Promise<model.LoginResponse>;

export function Register(arg1:Record<string, string>):Promise<model.User>;

export function SimulateDeviceLog(arg1:number):Promise<model.NetworkLog>;

export function SimulateDeviceMetric(arg1:number,arg2:string):Promise<model.Metric>;

export function UpdateConnection(arg1:model.Connection):Promise<void>;

export function UpdateReport(arg1:model.Reports):Promise<void>;

export function ValidateConfiguration(arg1:model.Configuration):Promise<void>;
