// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanupOldMetrics(arg1) {
  return window['go']['service']['Service']['CleanupOldMetrics'](arg1);
}

export function Create(arg1) {
  return window['go']['service']['Service']['Create'](arg1);
}

export function CreateConnection(arg1, arg2) {
  return window['go']['service']['Service']['CreateConnection'](arg1, arg2);
}

export function CreateDevice(arg1) {
  return window['go']['service']['Service']['CreateDevice'](arg1);
}

export function CreateReport(arg1) {
  return window['go']['service']['Service']['CreateReport'](arg1);
}

export function CreateTopologyElement(arg1) {
  return window['go']['service']['Service']['CreateTopologyElement'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['service']['Service']['DeleteConnection'](arg1);
}

export function DeleteReport(arg1) {
  return window['go']['service']['Service']['DeleteReport'](arg1);
}

export function GetActive(arg1) {
  return window['go']['service']['Service']['GetActive'](arg1);
}

export function GetAllConnections() {
  return window['go']['service']['Service']['GetAllConnections']();
}

export function GetAllDevices() {
  return window['go']['service']['Service']['GetAllDevices']();
}

export function GetAllLogs() {
  return window['go']['service']['Service']['GetAllLogs']();
}

export function GetAllMetrics() {
  return window['go']['service']['Service']['GetAllMetrics']();
}

export function GetAllReports() {
  return window['go']['service']['Service']['GetAllReports']();
}

export function GetAllTopology() {
  return window['go']['service']['Service']['GetAllTopology']();
}

export function GetByDeviceID(arg1) {
  return window['go']['service']['Service']['GetByDeviceID'](arg1);
}

export function GetByName(arg1) {
  return window['go']['service']['Service']['GetByName'](arg1);
}

export function GetConnectionById(arg1) {
  return window['go']['service']['Service']['GetConnectionById'](arg1);
}

export function GetConnectionsByDeviceId(arg1, arg2) {
  return window['go']['service']['Service']['GetConnectionsByDeviceId'](arg1, arg2);
}

export function GetDeviceById(arg1) {
  return window['go']['service']['Service']['GetDeviceById'](arg1);
}

export function GetLatestMetricsByDeviceId(arg1, arg2) {
  return window['go']['service']['Service']['GetLatestMetricsByDeviceId'](arg1, arg2);
}

export function GetLogsByDeviceId(arg1) {
  return window['go']['service']['Service']['GetLogsByDeviceId'](arg1);
}

export function GetMetricsByDeviceId(arg1) {
  return window['go']['service']['Service']['GetMetricsByDeviceId'](arg1);
}

export function GetMetricsByDeviceIdAndInterval(arg1, arg2, arg3, arg4) {
  return window['go']['service']['Service']['GetMetricsByDeviceIdAndInterval'](arg1, arg2, arg3, arg4);
}

export function GetRecentLogs(arg1) {
  return window['go']['service']['Service']['GetRecentLogs'](arg1);
}

export function GetReport(arg1) {
  return window['go']['service']['Service']['GetReport'](arg1);
}

export function Login(arg1) {
  return window['go']['service']['Service']['Login'](arg1);
}

export function Register(arg1) {
  return window['go']['service']['Service']['Register'](arg1);
}

export function SimulateDeviceLog(arg1) {
  return window['go']['service']['Service']['SimulateDeviceLog'](arg1);
}

export function SimulateDeviceMetric(arg1, arg2) {
  return window['go']['service']['Service']['SimulateDeviceMetric'](arg1, arg2);
}

export function UpdateConnection(arg1) {
  return window['go']['service']['Service']['UpdateConnection'](arg1);
}

export function UpdateReport(arg1) {
  return window['go']['service']['Service']['UpdateReport'](arg1);
}

export function ValidateConfiguration(arg1) {
  return window['go']['service']['Service']['ValidateConfiguration'](arg1);
}
