// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAlert(arg1) {
  return window['go']['main']['App']['DeleteAlert'](arg1);
}

export function DeleteConnection(arg1) {
  return window['go']['main']['App']['DeleteConnection'](arg1);
}

export function DeleteDevice(arg1) {
  return window['go']['main']['App']['DeleteDevice'](arg1);
}

export function GenerateAlertForDevice(arg1) {
  return window['go']['main']['App']['GenerateAlertForDevice'](arg1);
}

export function GenerateDevice() {
  return window['go']['main']['App']['GenerateDevice']();
}

export function ListAlerts() {
  return window['go']['main']['App']['ListAlerts']();
}

export function ListConnectionLogs(arg1) {
  return window['go']['main']['App']['ListConnectionLogs'](arg1);
}

export function ListConnectionMetrics(arg1) {
  return window['go']['main']['App']['ListConnectionMetrics'](arg1);
}

export function ListConnections() {
  return window['go']['main']['App']['ListConnections']();
}

export function ListDeviceLogs(arg1) {
  return window['go']['main']['App']['ListDeviceLogs'](arg1);
}

export function ListDeviceMetrics(arg1) {
  return window['go']['main']['App']['ListDeviceMetrics'](arg1);
}

export function ListDevices() {
  return window['go']['main']['App']['ListDevices']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Register(arg1, arg2, arg3) {
  return window['go']['main']['App']['Register'](arg1, arg2, arg3);
}

export function SaveAlert(arg1) {
  return window['go']['main']['App']['SaveAlert'](arg1);
}

export function SaveConnection(arg1) {
  return window['go']['main']['App']['SaveConnection'](arg1);
}

export function SaveDevice(arg1) {
  return window['go']['main']['App']['SaveDevice'](arg1);
}

export function ValidateToken(arg1) {
  return window['go']['main']['App']['ValidateToken'](arg1);
}
