// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {service} from '../models';

export function DeleteAlert(arg1:number):Promise<void>;

export function DeleteConnection(arg1:number):Promise<void>;

export function DeleteDevice(arg1:number):Promise<void>;

export function GenerateAlertForDevice(arg1:number):Promise<models.Alert>;

export function GenerateDevice():Promise<models.Device>;

export function ListAlerts():Promise<Array<models.Alert>>;

export function ListConnectionLogs(arg1:number):Promise<Array<models.Log>>;

export function ListConnectionMetrics(arg1:number):Promise<Array<models.Metric>>;

export function ListConnections():Promise<Array<models.Connection>>;

export function ListDeviceLogs(arg1:number):Promise<Array<models.Log>>;

export function ListDeviceMetrics(arg1:number):Promise<Array<models.Metric>>;

export function ListDevices():Promise<Array<models.Device>>;

export function Login(arg1:string,arg2:string):Promise<string>;

export function Register(arg1:string,arg2:string,arg3:string):Promise<models.User>;

export function SaveAlert(arg1:models.Alert):Promise<void>;

export function SaveConnection(arg1:models.Connection):Promise<models.Connection>;

export function SaveDevice(arg1:models.Device):Promise<models.Device>;

export function ValidateToken(arg1:string):Promise<service.TokenClaims>;
